version: "3.3"

services:
  oracle:
    build: ""
    env_file: .env
    image: n2n-oracle:latest
    working_dir: /deployment/
    command: sh start_oracle.sh
    volumes:
      - "${ORACLE_DATA}:/mountedcum"