version: "3.3"

services:
  oracle:
    build: .
    env_file: .env
    image: test-docker-day2:latest
    working_dir: /deployment/
    command: sh start_oracle.sh
    volumes:
      - "${ORACLE_DATA}:/mountedcum"